title: Diagonal County
description: Thoughts on history, ideas, and life.
url: "https://diagonalcounty.github.io"
baseurl: ""

theme: minima
show_excerpts: true

author: diagonalcounty

# Don't auto-link every page into the header nav
header_pages: []

exclude:
  - POST_TEMPLATE.txt
  - _templates
  - README.md
  - LICENSE
