title: Diagonal County
description: Thoughts on history, ideas, and life.
url: "https://diagonalcounty.github.io"
baseurl: ""

theme: minima
show_excerpts: true

minima:
  social_links:
    - platform: github
      user_url: "https://github.com/diagonalcounty"

header_pages: []

author: diagonalcounty
